name: "Merge PR to deploy"
permissions:
  id-token: write
  contents: read
  issues: read
on:
  workflow_dispatch:
  push:
    branches:
      - main

jobs:
  Plan:
    if: github.event.deployment.environment == 'infra-test' && github.event.deployment.payload.version
    uses: ./.github/workflows/pull-request.yml
    with:
      path: files/accounts/datascience/environments/eu-west-2/wise
      gh_environment: infra-test
    secrets:
      aws_role_to_assume: ${{ secrets.AWS_GITHUB_ACTION_ROLE }}
      aws_default_region: eu-west-2
      terraform_version: ${{ secrets.TERRAFORM_VERSION }}

  Deploy:
    needs: Plan
    if: github.event.deployment.environment == 'infra-test' && github.event.deployment.payload.version
    uses: ./.github/workflows/terraform-apply.yml
    with:
      path: files/accounts/datascience/environments/eu-west-2/wise
      gh_environment: infra-test
    secrets:
      aws_role_to_assume: ${{ secrets.AWS_GITHUB_ACTION_ROLE }}
      aws_default_region: eu-west-2
      terraform_version: ${{ secrets.TERRAFORM_VERSION }}